---
title: "A Title"
subtitle: "A Subtitle"
author: Mickaël Canouil, *Ph.D.*
institute: Inserm U1283 / CNRS UMR8199 / Institut Pasteur de Lille / Université de Lille
date: today
date-format: "dddd, [the] D[<sup style='font-size:65%;font-style:italic;'>th</sup>] [of] MMMM, YYYY"
format:
  revealjs:
    self-contained: true
    slide-number: c
    highlight-style: github
    theme: assets/umr1283.scss
    footer: <a href="https:/www.good.cnrs.fr/">www.good.cnrs.fr</a>
    logo: https://raw.githubusercontent.com/mcanouil/hex-stickers/main/SVG/umr1283_8199.svg
---

```{r, include = FALSE}
showtext::showtext_auto()
source(normalizePath("../../ggplot2/setup-ggplot2-umr1283.R"))
```

## Introduction

### Subtitle

`some code` and some text.  
A URL [www.good.cnrs.fr](https://www.good.cnrs.fr/).

```{r, echo = TRUE}
1 + 1
```

```{r, echo = TRUE}
x <- 1
y <- x + 1 #<<
y
```

## GGPLOT2 With `code`

```{r, echo = FALSE}
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) + geom_point()
```

# PART 1 With `code` {.center .center-x}

## New slide

With only text

{{< include assets/about.qmd >}}
