name: Update Submodules

on:
  schedule:
    - cron: "0 12 * * SUN"
  push:
    branches: main
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "ci: automatic weekly update"
          signoff: false
          branch: auto-detected-updates
          delete-branch: true
          title: "Automatic weekly update"
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      - name: Merge Pull Request
        if: ${{ steps.cpr.outputs.pull-request-number != '' }}
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: merge